apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${NS}-ingress
  namespace: ${NS}
spec:
  ingressClassName: nginx
  rules:
    - host: ${NS}.draweditor.com
      http:
        paths:
          - path: /ping
            pathType: Prefix
            backend:
              service:
                name: api-service
                port:
                  number: 3000
