export const configs = {
  RABBITMQ_URL: process.env.RABBITMQ_URL,
  MONGODB_URL: process.env.MONGODB_URL,

  JWT_ACCESS_TOKEN_SECRET: process.env.JWT_ACCESS_TOKEN_SECRET,
  JWT_ACCESS_TOKEN_EXPIRATION_TIME: process.env.JWT_ACCESS_TOKEN_EXPIRATION_TIME,

  TWILIO_ACCOUNT_SID: process.env.TWILIO_ACCOUNT_SID,
  TWILIO_AUTH_TOKEN: process.env.TWILIO_AUTH_TOKEN,

  OTP_MESSAGE: process.env.OTP_MESSAGE ?? 'Your verification code is {otp}'
}
