POST {{HOST_DEV}}/auth/otp/sms
content-type: application/json

{
  "phoneNumber": "+84967397077"
}

POST {{HOST_DEV}}/auth/otp/sms/verification
content-type: application/json

{
  "phoneNumber": "+84967397077",
  "otp": "772527"
}

POST {{HOST_DEV}}/sms/initiate-verification
content-type: application/json

{
  "phoneNumber": "+84967397077"
}

POST {{HOST_DEV}}/authentication/register
content-type: application/json

{
  "email": "test@gmail.com",
  "password": "dev"
}


POST {{HOST_DEV}}/authentication/login

POST http://staging.draweditor.com/api/authentication/login
content-type: application/json

{
  "email": "test@gmail.com",
  "password": "dev"
}

GET {{HOST_DEV}}/authentication

GET http://staging.draweditor.com/web

GET http://staging.draweditor.com/api/authentication
Authentication: edayJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwZmYxZWRhNS05M2NhLTQ5NmUtOThjZS1mZTgwZWJhZDQyNmMiLCJpYXQiOjE2Nzk5OTE1NjgsImV4cCI6MTY3OTk5NTE2OH0.VWZ4qO-bCIMdHzFZ-HXoOkTBRw-EG98zpviH_yeT5fQ
